apiVersion: "v1"
kind: "Pod"
metadata:
  name: "upone"
spec:
  containers:
    -
      name: "upone"
      image: "quay.io/glennswest/upone"
      volumeMounts:
        -
          mountPath: "/data"
          name: "uponevol"
  volumes:
    -
      name: "uponevol"
      persistentVolumeClaim:
        claimName: "pvcupone"

